### ISSUE TITLE
docs point to wrong repo

### ISSUE THREAD

**Issue by hellochar** [palantir/typesettable#39]
The docs at e.g. http://palantir.github.io/svg-typewriter/docs/classes/svgtypewriter.writers.writer.html say:

"Defined in /Users/askrodzki/Work/svg-typewriter-page/src/writer.ts:40"

We should update that to point to the correct location.

Side note (the link points to "https://github.com/endrjuskr/svg-typewriter/blob/gh-pages/src/writer.ts#L40", although it correctly redirects to palantir/svg-typewriter)

**Comment by themadcreator** [comment]
Docs have been regenerated
