### ISSUE TITLE
Auto adjust font size

### ISSUE THREAD

**Issue by endrjuskr** [palantir/typesettable#5]
Introduce functionality on `writer` that instead of putting ellipsis when text does not fit, try to adjust font size.

Need to check if setting font directly on `<text>` node will override CSS style.

**Comment by themadcreator** [comment]
This sounds quite expensive since we'd have to we-wrap the entire string if it doesn't fit at a different font size.

Plus, since you alluded to CSS overrides, we would now have to take control of font styles, not just measure them.

**Comment by themadcreator** [comment]
Also, how much do we reduce the font size if it doesn't fit? Do we keep trying until font-size = 0?

**Comment by hellochar** [comment]
We could just compute one "new font size" by finding the ratio of "actual width" / "width available" right? Might be useful, but not a big need imo

**Comment by themadcreator** [comment]
I'm not a fan of this feature. I'm gonna reject for now
